# Digital Ocean App Platform Configuration
# Deployment configuration for freezer-backend
name: freezer-app

services:
- name: api
  source_dir: /
  github:
    repo: freezer-backend
    branch: main
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  
  # Production Environment Variables
  envs:
  - key: ENVIRONMENT
    value: production
    
  - key: CORS_ORIGINS
    value: https://freezer-app-frontend.ondigitalocean.app
    
  - key: JWT_SECRET_KEY
    scope: SECRET
    # Generate with: python -c "import secrets; print(secrets.token_urlsafe(64))"
    
  - key: ACCESS_TOKEN_EXPIRE_MINUTES
    value: "60"
    
  - key: DATABASE_URL
    scope: SECRET
    # Will be provided by managed database connection
    
  # Optional performance settings  
  - key: DB_POOL_SIZE
    value: "10"
    
  - key: LOG_LEVEL
    value: "INFO"

# Managed PostgreSQL Database
databases:
- engine: PG
  name: freezer-db
  num_nodes: 1
  size: db-s-1vcpu-1gb
  version: "13"

# Static site for frontend (if needed)
static_sites:
- name: frontend
  source_dir: /
  github:
    repo: freezer-frontend
    branch: main
  build_command: npm run build
  output_dir: dist