# Docker Compose for Droplet Deployment
# Cost: ~$6/month Linode Nanode or DO Basic Droplet
version: '3.8'

services:
  # FastAPI Backend
  api:
    build: .
    container_name: freezer-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://freezer_user:${DB_PASSWORD}@db:5432/freezer_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # PostgreSQL Database
  db:
    image: postgres:13-alpine
    container_name: freezer-db
    environment:
      - POSTGRES_DB=freezer_db
      - POSTGRES_USER=freezer_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: freezer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ../freezer-frontend/dist:/usr/share/nginx/html
    depends_on:
      - api
    restart: unless-stopped

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: freezer-certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ../freezer-frontend/dist:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email -d your-domain.com

volumes:
  postgres_data: