"""Add item_notifications table for tracking notification state

Revision ID: 88573c8416f9
Revises: c70775dc65a4
Create Date: 2025-10-25 11:24:20.375041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88573c8416f9'
down_revision: Union[str, None] = 'c70775dc65a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
